//api wondi categoria de empresas
export const FETCHING_DATA_CATEGORY = "FETCHING_DATA_CATEGORY";
export const FETCHING_DATA_SUCCESS_CATEGORY = "FETCHING_DATA_SUCCESS_CATEGORY";
export const FETCHING_DATA_FAILURE_CATEGORY = "FETCHING_DATA_FAILURE_CATEGORY";
//api wondi empresas por categoria
export const FETCHING_DATA_SHOP = "FETCHING_DATA_SHOP";
export const FETCHING_DATA_SUCCESS_SHOP = "FETCHING_DATA_SUCCESS_SHOP";
export const FETCHING_DATA_FAILURE_SHOP = "FETCHING_DATA_FAILURE_SHOP";
//api wondi productos por empresa
export const FETCHING_DATA_SHOP_PRO = "FETCHING_DATA_SHOP_PRO";
export const FETCHING_DATA_SUCCESS_SHOP_PRO = "FETCHING_DATA_SUCCESS_SHOP_PRO";
export const FETCHING_DATA_FAILURE_SHOP_PRO = "FETCHING_DATA_FAILURE_SHOP_PRO";
//api wondi detalles empresa
export const FETCHING_DATA_SHOP_D = "FETCHING_DATA_SHOP_D";
export const FETCHING_DATA_SUCCESS_SHOP_D = "FETCHING_DATA_SUCCESS_SHOP_D";
export const FETCHING_DATA_FAILURE_SHOP_D = "FETCHING_DATA_FAILURE_SHOP_D";
//api wondi presupuestos
export const FETCHING_DATA_BUDGET = "FETCHING_DATA_BUDGET";
export const FETCHING_DATA_SUCCESS_BUDGET = "FETCHING_DATA_SUCCESS_BUDGET";
export const FETCHING_DATA_FAILURE_BUDGET = "FETCHING_DATA_FAILURE_BUDGET";
//api wondi presupuestos detalles
export const FETCHING_DATA_BUDGET_D = "FETCHING_DATA_BUDGET_D";
export const FETCHING_DATA_SUCCESS_BUDGET_D = "FETCHING_DATA_SUCCESS_BUDGET_D";
export const FETCHING_DATA_FAILURE_BUDGET_D = "FETCHING_DATA_FAILURE_BUDGET_D";
//api wondi sugerencias
export const FETCHING_DATA_SUGGESTIONS = "FETCHING_DATA_SUGGESTIONS";
export const FETCHING_DATA_SUCCESS_SUGGESTIONS = "FETCHING_DATA_SUCCESS_SUGGESTIONS";
export const FETCHING_DATA_FAILURE_SUGGESTIONS = "FETCHING_DATA_FAILURE_SUGGESTIONS";
//api wondi productos
export const FETCHING_DATA_PRODUCTS = "FETCHING_DATA_PRODUCTS";
export const FETCHING_DATA_SUCCESS_PRODUCTS = "FETCHING_DATA_SUCCESS_PRODUCTS";
export const FETCHING_DATA_FAILURE_PRODUCTS = "FETCHING_DATA_FAILURE_PRODUCTS";
//api wondi busqueda
export const FETCHING_DATA_SEARCH = "FETCHING_DATA_SEARCH";
export const FETCHING_DATA_SUCCESS_SEARCH = "FETCHING_DATA_SUCCESS_SEARCH";
export const FETCHING_DATA_FAILURE_SEARCH = "FETCHING_DATA_FAILURE_SEARCH";
//api wondi resultado
export const FETCHING_DATA_RESULT = "FETCHING_DATA_RESULT";
export const FETCHING_DATA_SUCCESS_RESULT = "FETCHING_DATA_SUCCESS_RESULT";
export const FETCHING_DATA_FAILURE_RESULT = "FETCHING_DATA_FAILURE_RESULT";

export const FETCH_MAIN = "FETCH_MAIN";
export const FETCH_SUCCEEDED = "FETCH_SUCCEEDED";
export const FETCH_FAILED = "FETCH_FAILED";
//api wondi detalle usuario
export const FETCHING_DATA_USER = "FETCHING_DATA_USER";
export const FETCHING_DATA_SUCCESS_USER  = "FETCHING_DATA_SUCCESS_USER";
export const FETCHING_DATA_FAILURE_USER = "FETCHING_DATA_FAILURE_USER";
//api wondi iniciar session
export const FETCHING_DATA_LOGIN = "FETCHING_DATA_LOGIN";
export const FETCHING_DATA_SUCCESS_LOGIN  = "FETCHING_DATA_SUCCESS_LOGIN";
export const FETCHING_DATA_FAILURE_LOGIN = "FETCHING_DATA_FAILURE_LOGIN";
//api wondi registrarse
export const FETCHING_DATA_SIGNUP = "FETCHING_DATA_SIGNUP";
export const FETCHING_DATA_SUCCESS_SIGNUP  = "FETCHING_DATA_SUCCESS_SIGNUP";
export const FETCHING_DATA_FAILURE_SIGNUP = "FETCHING_DATA_FAILURE_SIGNUP";
//api wondi inicio
	//Lista de productos con precios bajos (wondi select)
	export const FETCHING_DATA_BESTPRICE 		  = "FETCHING_DATA_BESTPRICE";
	export const FETCHING_DATA_SUCCESS_BESTPRICE  = "FETCHING_DATA_SUCCESS_BESTPRICE";
	export const FETCHING_DATA_FAILURE_BESTPRICE  = "FETCHING_DATA_FAILURE_BESTPRICE";
	//Lista de productos similares a tus busquedas
	export const FETCHING_DATA_SIMILARY 		  = "FETCHING_DATA_SIMILARY";
	export const FETCHING_DATA_SUCCESS_SIMILARY   = "FETCHING_DATA_SUCCESS_SIMILARY";
	export const FETCHING_DATA_FAILURE_SIMILARY   = "FETCHING_DATA_FAILURE_SIMILARY";
	//Lista de productos mas presupuestos en las ultimas 24 horas
	export const FETCHING_DATA_MOREBUDGET 		   = "FETCHING_DATA_MOREBUDGET";
	export const FETCHING_DATA_SUCCESS_MOREBUDGET  = "FETCHING_DATA_SUCCESS_MOREBUDGET";
	export const FETCHING_DATA_FAILURE_MOREBUDGET  = "FETCHING_DATA_FAILURE_MOREBUDGET";
	//Lista de productos mas buscados en general en las ultimas 24 horas
	export const FETCHING_DATA_BESTSEARCH 		   = "FETCHING_DATA_BESTSEARCH";
	export const FETCHING_DATA_SUCCESS_BESTSEARCH  = "FETCHING_DATA_SUCCESS_BESTSEARCH";
	export const FETCHING_DATA_FAILURE_BESTSEARCH  = "FETCHING_DATA_FAILURE_BESTSEARCH";
	//Lista de productos destacados para un usuario
	export const FETCHING_DATA_LISTXUSER 		  = "FETCHING_DATA_LISTXUSER";
	export const FETCHING_DATA_SUCCESS_LISTXUSER  = "FETCHING_DATA_SUCCESS_LISTXUSER";
	export const FETCHING_DATA_FAILURE_LISTXUSER  = "FETCHING_DATA_FAILURE_LISTXUSER";
	//Lista de productos destacados para un usuario full
	export const FETCHING_DATA_LISTXUSERFULL 		  = "FETCHING_DATA_LISTXUSERFULL";
	export const FETCHING_DATA_SUCCESS_LISTXUSERFULL  = "FETCHING_DATA_SUCCESS_LISTXUSERFULL";
	export const FETCHING_DATA_FAILURE_LISTXUSERFULL  = "FETCHING_DATA_FAILURE_LISTXUSERFULL";

//api wondi Promociones
export const FETCHING_DATA_PROMO = "FETCHING_DATA_PROMO";
export const FETCHING_DATA_SUCCESS_PROMO  = "FETCHING_DATA_SUCCESS_PROMO";
export const FETCHING_DATA_FAILURE_PROMO = "FETCHING_DATA_FAILURE_PROMO";
//api wondi Promociones producto
export const FETCHING_DATA_PROMO_PROD 		   = "FETCHING_DATA_PROMO_PROD";
export const FETCHING_DATA_SUCCESS_PROMO_PROD  = "FETCHING_DATA_SUCCESS_PROMO_PROD";
export const FETCHING_DATA_FAILURE_PROMO_PROD  = "FETCHING_DATA_FAILURE_PROMO_PROD";
//api wondi Sucursales
export const FETCHING_DATA_SUC 			= "FETCHING_DATA_SUC";
export const FETCHING_DATA_SUCCESS_SUC  = "FETCHING_DATA_SUCCESS_SUC";
export const FETCHING_DATA_FAILURE_SUC  = "FETCHING_DATA_FAILURE_SUC";
//api wondi restablecer contraseña
export const FETCHING_DATA_PASS 		 = "FETCHING_DATA_PASS";
export const FETCHING_DATA_SUCCESS_PASS  = "FETCHING_DATA_SUCCESS_PASS";
export const FETCHING_DATA_FAILURE_PASS  = "FETCHING_DATA_FAILURE_PASS";
//api wondi editar usuario
export const FETCHING_DATA_USEREDIT 		 = "FETCHING_DATA_USEREDIT";
export const FETCHING_DATA_SUCCESS_USEREDIT  = "FETCHING_DATA_SUCCESS_USEREDIT";
export const FETCHING_DATA_FAILURE_USEREDIT  = "FETCHING_DATA_FAILURE_USEREDIT";
//api wondi historial
export const FETCHING_DATA_HISTORY 		 = "FETCHING_DATA_HISTORY";
export const FETCHING_DATA_SUCCESS_HISTORY  = "FETCHING_DATA_SUCCESS_HISTORY";
export const FETCHING_DATA_FAILURE_HISTORY  = "FETCHING_DATA_FAILURE_HISTORY";
//api wondi preferencias usuario
export const FETCHING_DATA_PREFERENCES 		 = "FETCHING_DATA_PREFERENCES";
export const FETCHING_DATA_SUCCESS_PREFERENCES  = "FETCHING_DATA_SUCCESS_PREFERENCES";
export const FETCHING_DATA_FAILURE_PREFERENCES  = "FETCHING_DATA_FAILURE_PREFERENCES";
//api wondi promociones full (limitar a 6)
export const FETCHING_DATA_PROMOFULL 		  = "FETCHING_DATA_PROMOFULL";
export const FETCHING_DATA_SUCCESS_PROMOFULL  = "FETCHING_DATA_SUCCESS_PROMOFULL";
export const FETCHING_DATA_FAILURE_PROMOFULL  = "FETCHING_DATA_FAILURE_PROMOFULL";
//api detalles de un producto
export const FETCHING_DATA_PRODDET 		  	= "FETCHING_DATA_PRODDET";
export const FETCHING_DATA_SUCCESS_PRODDET  = "FETCHING_DATA_SUCCESS_PRODDET";
export const FETCHING_DATA_FAILURE_PRODDET  = "FETCHING_DATA_FAILURE_PRODDET";