//api wondi categoria de empresas
export const FETCHING_DATA_CATEGORY = "FETCHING_DATA_CATEGORY";
export const FETCHING_DATA_SUCCESS_CATEGORY = "FETCHING_DATA_SUCCESS_CATEGORY";
export const FETCHING_DATA_FAILURE_CATEGORY = "FETCHING_DATA_FAILURE_CATEGORY";
//api wondi empresas por categoria
export const FETCHING_DATA_SHOP = "FETCHING_DATA_SHOP";
export const FETCHING_DATA_SUCCESS_SHOP = "FETCHING_DATA_SUCCESS_SHOP";
export const FETCHING_DATA_FAILURE_SHOP = "FETCHING_DATA_FAILURE_SHOP";
//api wondi productos por empresa
export const FETCHING_DATA_SHOP_PRO = "FETCHING_DATA_SHOP_PRO";
export const FETCHING_DATA_SUCCESS_SHOP_PRO = "FETCHING_DATA_SUCCESS_SHOP_PRO";
export const FETCHING_DATA_FAILURE_SHOP_PRO = "FETCHING_DATA_FAILURE_SHOP_PRO";
//api wondi detalles empresa
export const FETCHING_DATA_SHOP_D = "FETCHING_DATA_SHOP_D";
export const FETCHING_DATA_SUCCESS_SHOP_D = "FETCHING_DATA_SUCCESS_SHOP_D";
export const FETCHING_DATA_FAILURE_SHOP_D = "FETCHING_DATA_FAILURE_SHOP_D";
//api wondi presupuestos
export const FETCHING_DATA_BUDGET = "FETCHING_DATA_BUDGET";
export const FETCHING_DATA_SUCCESS_BUDGET = "FETCHING_DATA_SUCCESS_BUDGET";
export const FETCHING_DATA_FAILURE_BUDGET = "FETCHING_DATA_FAILURE_BUDGET";
//api wondi presupuestos detalles
export const FETCHING_DATA_BUDGET_D = "FETCHING_DATA_BUDGET_D";
export const FETCHING_DATA_SUCCESS_BUDGET_D = "FETCHING_DATA_SUCCESS_BUDGET_D";
export const FETCHING_DATA_FAILURE_BUDGET_D = "FETCHING_DATA_FAILURE_BUDGET_D";
//api wondi sugerencias
export const FETCHING_DATA_SUGGESTIONS = "FETCHING_DATA_SUGGESTIONS";
export const FETCHING_DATA_SUCCESS_SUGGESTIONS = "FETCHING_DATA_SUCCESS_SUGGESTIONS";
export const FETCHING_DATA_FAILURE_SUGGESTIONS = "FETCHING_DATA_FAILURE_SUGGESTIONS";
//api wondi home/products
export const FETCHING_DATA_PRODUCTS = "FETCHING_DATA_PRODUCTS";
export const FETCHING_DATA_SUCCESS_PRODUCTS = "FETCHING_DATA_SUCCESS_PRODUCTS";
export const FETCHING_DATA_FAILURE_PRODUCTS = "FETCHING_DATA_FAILURE_PRODUCTS";
//api wondi search
export const FETCHING_DATA_SEARCH = "FETCHING_DATA_SEARCH";
export const FETCHING_DATA_SUCCESS_SEARCH = "FETCHING_DATA_SUCCESS_SEARCH";
export const FETCHING_DATA_FAILURE_SEARCH = "FETCHING_DATA_FAILURE_SEARCH";
//api wondi result
export const FETCHING_DATA_RESULT = "FETCHING_DATA_RESULT";
export const FETCHING_DATA_SUCCESS_RESULT = "FETCHING_DATA_SUCCESS_RESULT";
export const FETCHING_DATA_FAILURE_RESULT = "FETCHING_DATA_FAILURE_RESULT";
//*************************************Post**********************************************
export const FETCH_MAIN = "FETCH_MAIN";
export const FETCH_SUCCEEDED = "FETCH_SUCCEEDED";
export const FETCH_FAILED = "FETCH_FAILED";
//usuario
export const FETCHING_DATA_USER = "FETCHING_DATA_USER";
export const FETCHING_DATA_SUCCESS_USER  = "FETCHING_DATA_SUCCESS_USER";
export const FETCHING_DATA_FAILURE_USER = "FETCHING_DATA_FAILURE_USER";
//login
export const FETCHING_DATA_LOGIN = "FETCHING_DATA_LOGIN";
export const FETCHING_DATA_SUCCESS_LOGIN  = "FETCHING_DATA_SUCCESS_LOGIN";
export const FETCHING_DATA_FAILURE_LOGIN = "FETCHING_DATA_FAILURE_LOGIN";
//signup
export const FETCHING_DATA_SIGNUP = "FETCHING_DATA_SIGNUP";
export const FETCHING_DATA_SUCCESS_SIGNUP  = "FETCHING_DATA_SUCCESS_SIGNUP";
export const FETCHING_DATA_FAILURE_SIGNUP = "FETCHING_DATA_FAILURE_SIGNUP";
//home
export const FETCHING_DATA_HOME = "FETCHING_DATA_HOME";
export const FETCHING_DATA_SUCCESS_HOME  = "FETCHING_DATA_SUCCESS_HOME";
export const FETCHING_DATA_FAILURE_HOME = "FETCHING_DATA_FAILURE_HOME";